### ISSUE TITLE
ADD A "NEW EMPTY FILE" ENTRY TO NAUTILUS 

### ISSUE THREAD

**Issue by gargullia** [NicolasBernaerts/ubuntu-scripts#10]
http://www.webupd8.org/2012/11/add-new-empty-file-entry-to-nautilus-36.html

**Comment by gargullia** [comment]
http://www.webupd8.org/2012/11/add-new-empty-file-entry-to-nautilus-36.html

**Comment by NicolasBernaerts** [comment]
Hi garguilla,

You are right, this feature is really missing in Nautilus.
I was thinking for some time about adding it to my standard setup.

So, I've written a simple guide to setup Nautilus environment to get back this feature.
I've added some extra functionnalities (multiple document type & use of models).

It is available at http://bernaerts.dyndns.org/linux/344-nautilus-new-document-creation-menu

Let me know it it suits your need.

Cheers.
