### ISSUE TITLE
Vidstab using UI makes only a white video

### ISSUE THREAD

**Issue by Aslanex** [NicolasBernaerts/ubuntu-scripts#11]
Hi,

I'm trying to stabilize this video with the Rotation and stabilization script. I have already used it on some other videos from other cameras, but this one, as well as others in this format, produces just a white clip. I can choose the stabilization parameters, then it shows the loading bar and after a second, it closes and the video is encoded in the background just to white. The problem seems to be in somehow skipping of the analyzing phase.

However, when I stabilize it only via terminal, everything works well. I've attached the problematic video here.

[video.zip](https://github.com/NicolasBernaerts/ubuntu-scripts/files/299476/video.zip)

**Comment by NicolasBernaerts** [comment]
Hi,

I've tried to stabilize attached video and it works perfectly fine on my 14.04 Ubuntu Gnome laptop.
Here are the versions of main tools : 

$ avconv
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
Hyper fast Audio and Video encoder
usage: avconv [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man avconv'
$ melt -version
melt 0.9.3
Copyright (C) 2002-2013 Ushodaya Enterprises Limited
<http://www.mltframework.org/>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Aslanex** [comment]
Hi,

it's strange. I have the same versions except for melt, which is 0.9.9. That could be the problem, but I have no idea what could be wrong… Anyway, thanks for the answer.
