### ISSUE TITLE
Recent rename broke blog links

### ISSUE THREAD

**Issue by eddy-geek** [NicolasBernaerts/ubuntu-scripts#12]
http://bernaerts.dyndns.org/linux/76-gnome/283-gnome-shell-install-extension-command-line-script

now has broken links due to https://github.com/NicolasBernaerts/ubuntu-scripts/commit/7e3e2b0ff500cdc33f97bdc59b50ded8b9edc567

**Comment by NicolasBernaerts** [comment]
Hi eddy-geek,
This article is obsolete, that's why I don't maintain it anymore.
It has been replaced by http://bernaerts.dyndns.org/linux/76-gnome/345-gnome-shell-install-remove-extension-command-line-script
