### ISSUE TITLE
can't convert a Transport Stream file from VDR

### ISSUE THREAD

**Issue by martinkg** [NicolasBernaerts/ubuntu-scripts#15]
I want to convert a .ts file recorded with VDR (Video Disc Recorder), but this fails with the error message:

video-convert2mkvaac: line 209: 32776 (0x8008): syntax error in expression (error token is "(0x8008)")
mediainfo file is attached.

[The_Italian_Job_-_Jagd_auf_Millionen.txt](https://github.com/NicolasBernaerts/ubuntu-scripts/files/504357/The_Italian_Job_-_Jagd_auf_Millionen.txt)

**Comment by NicolasBernaerts** [comment]
Hi,

Sorry but the script has not been designed for transport streams where video and audio tracks could be malformed. Mostly mkvmerge will crash because of that.
You should use a conversion tools to get a track in .mp4, .mkv, .avi, ... and then use the script.
