### ISSUE TITLE
[Feature request] Action "update extension" in mozilla-extension-manager script

### ISSUE THREAD

**Issue by MurzNN** [NicolasBernaerts/ubuntu-scripts#19]
Thanks for so useful mozilla-extension-manager script! I don't understand why this feature is not available in Firefox core.
Now I can easily install and remove extensions via command line. But after installing, seems extensions stay on old version after new releases, because Firefox users have no write access to global extension folder.
How can I update version of extension via command line in your script?

If no way now, can you add it in future versions? Thanks!

**Comment by NicolasBernaerts** [comment]
Hi, I don't really understand what doesn't work.
On what system are you using the script ?
Is it using sudo ?

**Comment by MurzNN** [comment]
> I don't understand why this feature is not available in Firefox core.
- this is opinion not about your script, but about Firefox - why Mozilla don't do this in Firefox core. Your script works well, thanks!

This issue is about new feature request: now `mozilla-extension-manager` can install or remove extension. But I need new action `update` that download and install fresh version of xpi file. Can you do this?

**Comment by NicolasBernaerts** [comment]
I added --update option that install or update extension.
--install option only install without update (as before).
It should solve your problem.
Cheers

**Comment by MurzNN** [comment]
Thanks, I test it, but there are the problem that it always ask to overwrite files:
```
installing https://addons.mozilla.org/firefox/downloads/latest/clear-site-cache/addon-589468-latest.xpi
replace /usr/lib/firefox-addons/extensions/jid1-6CLCC0H1teLcrQ@jetpack/META-INF/mozilla.rsa? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
```
Would be good to cleanup old version files (for remove files, not exists in new versions of extension), or force overwrite files on `--update` action and after this - remove obsolete files.

**Comment by NicolasBernaerts** [comment]
I added previous extension clenup in the --update option.
You should get rid of overwrite mesages.

**Comment by MurzNN** [comment]
Yes, thanks, all works well!
