### ISSUE TITLE
[mozilla-extension-manager] Download extension xpi file to tmp folder

### ISSUE THREAD

**Issue by MurzNN** [NicolasBernaerts/ubuntu-scripts#21]
Seems that your script downloads addon.xpi in current folder (and removes it after install). But if user have no write access to this folder, process will broken.
Can we download extension into /tmp folder, in which all users have write access?

**Comment by NicolasBernaerts** [comment]
You are right, extension was downloaded to current directory.
I've modified the script to handle it in temporary directory.

**Comment by MurzNN** [comment]
Yes, thanks!
