### ISSUE TITLE
[mozilla-extension-manager] Action to check that extension already installed and list all installed extensions

### ISSUE THREAD

**Issue by MurzNN** [NicolasBernaerts/ubuntu-scripts#22]
Many Firefox extension files have very strange names like {e4a8a97b-f2ed-450b-b12d-ee082ba24781}.xpi so there are too difficult to understand which extension already exist, or which extension contains current file.

Please add action to check that extension already exists.
Also will be good to have action for output table with names of all installed extension (and maybe type local/global, and version).

**Comment by NicolasBernaerts** [comment]
I added --list parameter in V2.4
It should be an answer to your request.
Cheers

**Comment by MurzNN** [comment]
Thanks, all works well!
