### ISSUE TITLE
[mozilla-extension-manager] Ability to set extension path folder manually from argument

### ISSUE THREAD

**Issue by MurzNN** [NicolasBernaerts/ubuntu-scripts#23]
Please add ability to set extension path folder manually from argument like:
```
mozilla-extension-manager --install --path="/mnt/pxe-system-root/usr/lib/firefox-addons/extensions"
```
or environment variable.
I have PXE netboot environment in custom folder, and must install extension on server to guest system root disk, mounted to custom folder.

**Comment by NicolasBernaerts** [comment]
It has been added in the v2.3.
You now have a --path parameter.
Let me know if it solves your issue.

**Comment by MurzNN** [comment]
Thanks, this works well now!
