### ISSUE TITLE
[mozilla-extension-manager] Unable to install extension with --user option

### ISSUE THREAD

**Issue by lrgn** [NicolasBernaerts/ubuntu-scripts#28]
Dear Nicolas,

When I use the mozilla-extension-manager with the --user option, I get the following errors:

`$ mozilla-extension-manager --firefox --user --install https://update.adblockplus.org/latest/adblockplusfirefox.xpi`
`/usr/local/sbin/mozilla-extension-manager: ligne 311:  : commande introuvable`
`/usr/local/sbin/mozilla-extension-manager: ligne 314:  : commande introuvable`
`[success] install firefox user extension Adblock Plus, uid={d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}, version=2.9.1`
`$`

And the extension is not installed. After looking into the script, it seems that bash is not able to execute a command when starts by an empty `"${EXT_SUDO}"`, IE when the --system option is not set:

Line 311:
`"${EXT_SUDO}" cp -f "${ADDON_XPI}" "${EXT_PATH}/../${EXT_UID}.xpi"`

Line 314:
`"${EXT_SUDO}" unzip -qq "${ADDON_XPI}" -d "${EXT_PATH}/${EXT_UID}"`

My version of bash is 4.3.48.

A quick workaround I'm currently using is to remove the `"${EXT_SUDO}"`, as I only install the extensions on my user.

Could you please have a look into this ?

Thank you,
LRGN

**Comment by NicolasBernaerts** [comment]
Hello,
I've never met this problem, thanks for the feedback.
In v2.5, I changed handling of sudo commands for more compatibility.
Could you please tell me if it's ok for you now ?

**Comment by lrgn** [comment]
Hi Nicolas,

I tried again with the new version, and it works perfectly now. Thank you for your quick help, and for providing this very useful script.

Have a nice day.
Best regards,
LRGN
