### ISSUE TITLE
generate-booklet script can accidentally remove the source file

### ISSUE THREAD

**Issue by vedgy** [NicolasBernaerts/ubuntu-scripts#29]
https://github.com/NicolasBernaerts/ubuntu-scripts/blob/e05a1b138250177148cdd4db5e575702cef95529/pdf/generate-booklet#L94

https://github.com/NicolasBernaerts/ubuntu-scripts/blob/e05a1b138250177148cdd4db5e575702cef95529/pdf/generate-booklet#L109

The _generate-booklet_ script contains a **critical** bug: the original non-pdf file is removed if the `unoconv` command fails (!). If `unoconv` fails, the `FILETMP="${FILE}"` expression is executed, and so at the end of the script the original file is deleted. I've accidentally deleted an important file because of the bug.

A simple bug fix could be: replace `[ "${TYPE}" != "pdf" ] &&` with an `if-else` statement. In addition an additional check/assertion can be added before calling `rm`: `"${FILETMP}"` must not be equal to `"${FILE}"`. Another possible safety precaution is adding `set -e` at the top of the script (this may require other script modifications if it relies on proceeding after some command's failure).

**Comment by NicolasBernaerts** [comment]
Hi Igor,
Thanks for the feedback. You are right, in case of unoconv failure, your original file may be lost.
I've modified the script in this way : 
1. If file is not PDF, a temporary PDF file is generated.
2. Then conversion source is defined as original PDF or temporary one.
3. Finally, after conversion, temporary PDF is removed.
This should solve the issue.
Cheers

**Comment by NicolasBernaerts** [comment]
Hi Igor,
First **rm** is having no option as file exists and is empty.
Second one is having **-f** as according to the config, file has been created by unoconv or not. option **-f** avoid error if file doesn't exist.
I never met with any failure with **mktemp**. That's why I never deal with it in my scripts.
To be on the safe side I added a test before **unoconv**.

**Comment by vedgy** [comment]
Hi Nicolas,

* You are right about `rm`. Thanks for the explanation.

* I'd go with a simpler separate test in the `mktemp` case though. Such as `[ "${FILE_TMP}" != "" ] || exit 2`. Makes analyzing all the possible script behaviors simpler. Also an excerpt from a [Bash guide](http://mywiki.wooledge.org/BashGuide/TestsAndConditionals?highlight=(conditional)#Conditional_Blocks_.28if.2C_test_and_.5B.5B.29):

> Don't ever use the -a or -o tests of the [ command. Use multiple [ commands instead (or use [[ if you can). POSIX doesn't define the behavior of [ with complex sets of tests, so you never know what you'll get.

**Comment by vedgy** [comment]
Or even simpler:

`FILE_TMP=$(mktemp -t XXXXXXXX.pdf) && rm "${FILE_TMP}" || exit 2`

**Comment by NicolasBernaerts** [comment]
This is what I just tested this morning  :-)
I've updated the script with double [[ ]] and mktemp test.
Cheers.

**Comment by vedgy** [comment]
Thanks for improving the script!
I'll close this issue after some testing later, but if you tested the script carefully yourself, feel free to close it earlier.
