### ISSUE TITLE
Unable to encode videos in "ě" folders

### ISSUE THREAD

**Issue by Aslanex** [NicolasBernaerts/ubuntu-scripts#34]
When encoding any file with a path containing letter "ě", the rendering dialog disappears a second after rendering starts.

**Comment by NicolasBernaerts** [comment]
Hi,
What script are you talking about ?

**Comment by Aslanex** [comment]
Sorry, I'm talking about video-stabilize.

**Comment by NicolasBernaerts** [comment]
I've changed file path handling with sed. Is it working ok now ?

**Comment by Aslanex** [comment]
Sorry, as I am now on Ubuntu 17.10 the script does not work and I am not able to check the issue.
