### ISSUE TITLE
Allow install gnome extensions even if older version

### ISSUE THREAD

**Issue by e-minguez** [NicolasBernaerts/ubuntu-scripts#36]
Add a "--unsafe" flag or something similar to avoid messages like:

```
Gnome Shell version is 3.26
Extension System Monitor is not available for this version.
Available versions are :
3.10 3.12 3.14 3.16 3.18 3.20 3.22 3.24
```

It seems gnome is not checking compatibility anymore. See [here](https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/204) for more info.

**Comment by NicolasBernaerts** [comment]
Hi Eduardo,
I've added latest to --version to force installation of latest version available.
For example :
    # gnomeshell-extension-manage --install --version latest --user --extension-id 442
It should solve the purpose.
Cheers

**Comment by e-minguez** [comment]
Nice! I'll try it and let you know, but I think you should create a dedicated repo for that script because it worth it. Add some automation to build packages (I have this for Fedora https://github.com/e-minguez/rpms/tree/master/gnomeshell-extension-manage ). I'll be happy to collaborate if you want to create it! Thanks for your work!
