### ISSUE TITLE
Mad Catz (M.O.J.O) - usb vendorID

### ISSUE THREAD

**Issue by dide0** [NicolasBernaerts/ubuntu-scripts#38]
Hey,

The Mad Catz M.O.J.O has "0x0738" as USB vendorID

**Comment by NicolasBernaerts** [comment]
Hi dide0,
You had to add it to 51-android.rules only ?
Or also to adb_usb.ini ?

**Comment by dide0** [comment]
Hey @NicolasBernaerts,

I've added the vendorID in both files but my Mad Catz device is still not recognized over ADB. 

> On modern computer, most of the USB ports are USB3 and there is an incompatibility between some Android devices and USB3 ports. 
> This problem must be software related, as one of my phone is not recognized thru adb but is fully recognized thru fastboot on the same USB port !

Going to get a USB hub in the next few weeks, thanks for that tip :)

**Comment by NicolasBernaerts** [comment]
Updated in both files
