### ISSUE TITLE
[mozilla-extension-manager] Does not work with FF 60

### ISSUE THREAD

**Issue by skyline-ch** [NicolasBernaerts/ubuntu-scripts#39]
Google translation

Hello,
I have a problem with the script, it works fine, whenever it seems that Firefox have changed are working for add-on / extention.
After many attempts, I found that you should not extract the .xpi archive, just rename it with the UUID.

example for:
Bitwarden (https://addons.mozilla.org/en/firefox/addon/bitwarden-password-manager/)
once download -> bitwarden_free_password_manager-1.27.0-fx.xpi
rename to work: {446900e4-71c2-419f-a6a7-df9c091e268b} .xpi

Ubuntu 18.04 LTS
FireFox 60.0.2

#####################################################################
Original

Bonjour, 
J'ai un souci avec le script, il fonctionne correctement, toute fois il semble que Firefox ai changer sont fonctionnement pour les add-on/extention.
Après de nombreuse tentative, j'ai trouver qu'il ne faut pas extraire l’archive .xpi, juste la renommer avec le UUID.

exemple pour :
Bitwarden  (https://addons.mozilla.org/fr/firefox/addon/bitwarden-password-manager/)
une fois télécharger -> bitwarden_free_password_manager-1.27.0-fx.xpi
renommer pour fonctionner : {446900e4-71c2-419f-a6a7-df9c091e268b}.xpi

Ubuntu 18.04 LTS
FireFox 60.0.2

**Comment by NicolasBernaerts** [comment]
Merci Michel pour ce retour.

Je vais regarder et adapter le script par rapport à ce nouveau comportement.

Très bon weekend.

Nicolas

**Comment by skyline-ch** [comment]
Supère, merci pour la réactivité.

J'avais penser pour garder la compatibilité d'ajouter une option extract ou no-extract.

Par contre j'ai pas vérifier sur Thunderbird si le fonctionnement as aussi changer.

**Comment by NicolasBernaerts** [comment]
Hello Michel,

J'ai finalement complètement ré-écrit le script pour gérer firefox 60+.
Le nouveau script est **firefox-extension-manager**
Il ne gère plus que Firefox car Thunderbird semble maintenant gérer les extensions d'une manière différente de Firefox.
Merci de me signaler si tout est ok coté Firefox.

**Comment by skyline-ch** [comment]
Merci pour les modifications, j'ai pas encore eu le temps de tester, j'ai un mois d'aout charger, je te redis dès que j'aurais fais les testes

**Comment by skyline-ch** [comment]
Bonjour Nicolas, 
j'ai pus faire des test aujourd'hui, l'installation des add.on avec le paramètre --system est ok, par contre avec --user cela ne fonctionne pas.

sur une installation fraiche il semble que le dossier des extensions n'est pas existent et donc pose problème pour l'installation via ton script : 
voici quelques exemples de commande lancer dans la console

`ubuntu-test@ubuntutest-VirtualBox:~/PostinstallUbuntu-v0.13$ firefox-extension-manager --install --user --url https://addons.mozilla.org/fr/firefox/addon/containerise/
cp: impossible de créer le fichier standard '/home/ubuntu-test/.mozilla/firefox/68p6vz0v.default-1535817094727/extensions/containerise@kinte.sh.xpi': Aucun fichier ou dossier de ce type
cp: impossible de créer le fichier standard '/home/ubuntu-test/.mozilla/firefox/68p6vz0v.default-1535817094727/extensions/containerise@kinte.sh.xpi': Aucun fichier ou dossier de ce type
[success] Containerise installed/updated in user mode, version 2.5.0, uid containerise@kinte.sh
ubuntu-test@ubuntutest-VirtualBox:~/PostinstallUbuntu-v0.13$ sudo firefox-extension-manager --install --user --url https://addons.mozilla.org/fr/firefox/addon/containerise/
cp: impossible de créer le fichier standard '/home/ubuntu-test/.mozilla/firefox/68p6vz0v.default-1535817094727/extensions/containerise@kinte.sh.xpi': Aucun fichier ou dossier de ce type
cp: impossible de créer le fichier standard '/home/ubuntu-test/.mozilla/firefox/68p6vz0v.default-1535817094727/extensions/containerise@kinte.sh.xpi': Aucun fichier ou dossier de ce type
[success] Containerise installed/updated in user mode, version 2.5.0, uid containerise@kinte.sh
ubuntu-test@ubuntutest-VirtualBox:~/PostinstallUbuntu-v0.13$ firefox-extension-manager --install --user --url https://addons.mozilla.org/fr/firefox/addon/flagfox/
cp: impossible de créer le fichier standard '/home/ubuntu-test/.mozilla/firefox/68p6vz0v.default-1535817094727/extensions/{1018e4d6-728f-4b20-ad56-37578a4de76b}.xpi': Aucun fichier ou dossier de ce type
cp: impossible de créer le fichier standard '/home/ubuntu-test/.mozilla/firefox/68p6vz0v.default-1535817094727/extensions/{1018e4d6-728f-4b20-ad56-37578a4de76b}.xpi': Aucun fichier ou dossier de ce type
[success] Flagfox installed/updated in user mode, version 6.1.3, uid {1018e4d6-728f-4b20-ad56-37578a4de76b}
`
Si je crée manuellement le dossier "extensions" et lance l'installation d'un addon, l'installation se fais bien mais il est désactiver.
Donc je pense qu'il faudrait vérifier la présence du dossier, si non existent le créer, et si tu peux activer les addon en user par défaut se serais top, car pour un ou deux c'est pas un souci mais si il faut en activer des dizaines c'est plus lourd.

Pour les installations system il sont activer par défaut

Merci encore pour tout le travail

PS: Firefox 61.0.1 (64 bits)

**Comment by NicolasBernaerts** [comment]
Bonjour Michael,

J'ai modifié le script pour créer automatiquement le répertoire des extensions si nécessaire si le profil utilisateur existe. Cela devrait régler le problème.

Bon week-end.

**Comment by skyline-ch** [comment]
Bonsoir Nicolas,
Merci pour tout le travail, je confirme que c'est ok.
J'ai juste remarquer que si FF n'a jamais été lancé, le dossier .mozilla n'existe pas et du coup l’installation des add-on user ne fonctionne pas.
Donc dans mon script j'ai simplement lancer FF en fin d'installation de ton script, se qui me permet de faire créer le dossier .mozilla.
Donc une amélioration possible serais a l'installation d'un add-on user vérifier si le dossier existe, si non lancer FF et éventuellement le refermer.

Encore merci

**Comment by NicolasBernaerts** [comment]
Hi Michael,
I've added a --allow-create parameter to do the job of user profile creation.
With this option, if there is no $HOME/.mozilla/firefox directory : 
* it launches firefox
* waits for 5 seconds
* kills it
These actions should create user profile.
It should allow you to install user space extension, even on a brand new machine where firefox has never been launched. Just let me nkow if its ok.
Cheers
