### ISSUE TITLE
gnome shell-extension-install script returns "unknown parameter" for shell and extension params

### ISSUE THREAD

**Issue by GrayedFox** [NicolasBernaerts/ubuntu-scripts#40]
Hi there, thanks for the great script - came across it when reading your post over [here](http://bernaerts.dyndns.org/linux/76-gnome/283-gnome-shell-install-extension-command-line-script).

Two things - the link in the post should be updated to:
- https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/gnomeshell-extension-manage

Annnd... I can't get it to work! Following example commands both output `Unknown Parameter`

```
shell-extension-install $(echo $(gnome-shell --version) | grep -Eo '[0-9]?[0-9]\.[0-9]?[0-9]') 779
```

Should install Clipboard Indicator extension, based on current gnome shell version

Manually:

```
shell-extension-install 3.28 779
```

Also outputs:

```
Unknown parameter 3.28
Unknown parameter 779
```

**Comment by GrayedFox** [comment]
TBH I would expect the command to fail, since the extension only has a version for 3.26, but that's okay since I'm also adding it to an Ubuntu install script and would prefer this behaviour :dancer:

**Comment by NicolasBernaerts** [comment]
Hi,
The article you pointed out is obsolete. A link to the new one was published in the header.
To avoid any error, I've unpublished it.
The new article is available at
http://bernaerts.dyndns.org/linux/76-gnome/345-gnome-shell-install-remove-extension-command-line-script 
If you follow it, everything should work.
Cheers

**Comment by GrayedFox** [comment]
Totally solved it, and failed with a nicely formatted error message listing candidates for the extension (as expected).

Thank you! Don't know how I missed that header... but I suppose this is why we automate things - humans are so error prone huh?

Cheers
