### ISSUE TITLE
"USB port is of unknown type. Try to use another USB port."

### ISSUE THREAD

**Issue by LinArcX** [NicolasBernaerts/ubuntu-scripts#43]
Hi. thank you for this greate collection. i want to use mtp-declare script. after two steps and recognize my device in sterp 3 i got following error:
`"USB port is of unknown type. Try to use another USB port."`
How to fix it?
Android device: huawei g8
OS: arch linux
wm: i3

**Comment by NicolasBernaerts** [comment]
Hi LinArcX,
mtp-declare is an old script which was written for Ubuntu 12.04 and 14.04 at the time MTP was not handled properly. Under 16.04 or 18.04 you should not need it anymore.
I do not maintain it anymore.
Sorry

**Comment by NicolasBernaerts** [comment]
LinArcX,
I noticed that my laptop is having uhci USB ports.
So I added this USB type support in the script.
Hope it helps ...
