### ISSUE TITLE
Add `LICENSE` file

### ISSUE THREAD

**Issue by tukusejssirs** [NicolasBernaerts/ubuntu-scripts#53]
What is the licence? Could you add a `LICENSE` file please?

**Comment by NicolasBernaerts** [comment]
What for exactly ?

Le jeu. 9 janv. 2020 à 13:31, Tukusej’s Sirs <notifications@github.com> a
écrit :

**Comment by tukusejssirs** [comment]
For using/forking/modifying your scripts. :smiley:

**Comment by NicolasBernaerts** [comment]
You can fork it on GitHub without any problem :-)

Le jeu. 9 janv. 2020 à 13:35, Tukusej’s Sirs <notifications@github.com> a
écrit :

**Comment by tukusejssirs** [comment]
Should I presume it as GPLv3 licensed? :smiley:

**Comment by NicolasBernaerts** [comment]
You should ... :-)

Le jeu. 9 janv. 2020 à 13:45, Tukusej’s Sirs <notifications@github.com> a
écrit :
