### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by AGenchev** [NicolasBernaerts/ubuntu-scripts#55]
On XUbuntu 20.04 LTS it installs OK, makes autostart entry, but when I execute it from terminal (to save the layout initially), i get error:
/usr/local/sbin/update-monitor-position: line 61: syntax error: unexpected end of file
and there is no ~/.config/monitors.xml created
If that matters, I use arandr to design the screen layout and removed/replaced the xfce4 utility with /sbin/true, because it pops a new window each 5 seconds or so, which is...

**Comment by NicolasBernaerts** [comment]
Hello,
It's an old fix that I developed because of a 16.04 bug.
Do you really still need that fix for 20.04 ?

**Comment by AGenchev** [comment]
Well, I needed it, but I managed to find another workaround for myself by digging into the settings editor for XFconf and selecting 'default' and fallback settings for desktop profiles.

**Comment by rthickling** [comment]
This is still a problem on 20.04 (I'm using Pop_OS based on Ubuntu 20.04).
