### ISSUE TITLE
missing reference

### ISSUE THREAD

**Issue by xpseudonym** [NicolasBernaerts/ubuntu-scripts#57]
http://bernaerts.dyndns.org/linux/76-gnome/345-gnome-shell-install-remove-extension-command-line-script
Referenced here:
https://github.com/NicolasBernaerts/ubuntu-scripts/blob/master/ubuntugnome/gnomeshell-extension-manage
Doesn't exist:
```
Not Found

The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by calico-cat968** [comment]
The current link is: 
http://www.bernaerts-nicolas.fr/linux/
And in your case:
http://www.bernaerts-nicolas.fr/linux/76-gnome/345-gnome-shell-install-remove-extension-command-line-script

See `README.md` in https://github.com/NicolasBernaerts/ubuntu-scripts

**Comment by xpseudonym** [comment]
Many thanks

**Comment by calico-cat968** [comment]
No problem. It seems links in a number of other scripts and readme files in this repo also haven't been updated so don't close this issue yet.

**Comment by NicolasBernaerts** [comment]
You are right, site has been moved from http://bernaerts.dyndns.org/ to http://www.bernaerts-nicolas.fr/
All links within site have been preserved.
