### ISSUE TITLE
unnecessary dependencies in generated-booklet

### ISSUE THREAD

**Issue by myguidingstar** [NicolasBernaerts/ubuntu-scripts#9]
Thanks for this very handy script. However I think installing texlive-extra-utils package is overkill. Pdfjam is enough
http://packages.ubuntu.com/search?keywords=pdfjam
https://github.com/NicolasBernaerts/ubuntu-scripts/blob/master/pdf/generate-booklet#L24
also, unoconv should be optional
Thoughts?

**Comment by NicolasBernaerts** [comment]
Hi,
You are right.
Under xenial and trusty, texlive-extra-utils provides all needed files.
You don't need pdfjam package anymore.
Article and install scripts have been updated to remove pdfjam dependency few months back.
